import express from "express";
import { verifyApiKey } from "../middlewares/authMiddleware.js";
import { getRooms, getRoomById, createRoom, updateRoom, deleteRoom } from "../controllers/room.controller.js";
const router = express.Router();
router.get("/", verifyApiKey, getRooms);
router.get("/:id", verifyApiKey, getRoomById);
router.post("/", verifyApiKey, createRoom);
router.put("/:id", verifyApiKey, updateRoom);
router.delete("/:id", verifyApiKey, deleteRoom);
export default router;